#############################################################################
# Makefile for building: TestIRM
# Generated by qmake (2.01a) (Qt 4.7.2) on: Mon Oct 3 14:27:31 2011
# Project:  TestRPC.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile TestRPC.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -pthread -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pixman-1 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -pthread -I/usr/include/atk-1.0 -I/usr/include/pango-1.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/cairo -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/pixman-1 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4 -Isrc/common -Isrc/rpc -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lboost_thread-mt -pthread -L/usr/lib/x86_64-linux-gnu -lgtk-x11-2.0 -lgdk-x11-2.0 -latk-1.0 -lgio-2.0 -lpangoft2-1.0 -lpangocairo-1.0 -lgdk_pixbuf-2.0 -lm -lcairo -lpango-1.0 -lfreetype -lfontconfig -lgobject-2.0 -lgmodule-2.0 -lgthread-2.0 -lrt -lglib-2.0 -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/rpc/RPC.cpp \
		src/master/MasterChannel.cpp \
		src/master/MasterStub.cpp \
		src/slave/SlaveChannel.cpp \
		src/slave/SlaveStub.cpp \
		src/slave/GtkSlave.cpp 
OBJECTS       = RPC.o \
		MasterChannel.o \
		MasterStub.o \
		SlaveChannel.o \
		SlaveStub.o \
		GtkSlave.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		TestRPC.pro
QMAKE_TARGET  = TestIRM
DESTDIR       = 
TARGET        = TestIRM

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: TestRPC.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/link_pkgconfig.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile TestRPC.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/link_pkgconfig.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug QMLJSDEBUGGER_PATH=/usr/share/qtcreator/qml/qmljsdebugger -o Makefile TestRPC.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/TestIRM1.0.0 || $(MKDIR) .tmp/TestIRM1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/TestIRM1.0.0/ && $(COPY_FILE) --parents Protocol.h Channel.h Data.h Packet.h Requester.h Responder.h Router.h Stub.h RPC.h src/slave/SlaveChannel.h src/slave/SlaveStub.h src/master/MasterChannel.h src/master/MasterStub.h .tmp/TestIRM1.0.0/ && $(COPY_FILE) --parents src/rpc/RPC.cpp src/master/MasterChannel.cpp src/master/MasterStub.cpp src/slave/SlaveChannel.cpp src/slave/SlaveStub.cpp src/slave/GtkSlave.cpp .tmp/TestIRM1.0.0/ && (cd `dirname .tmp/TestIRM1.0.0` && $(TAR) TestIRM1.0.0.tar TestIRM1.0.0 && $(COMPRESS) TestIRM1.0.0.tar) && $(MOVE) `dirname .tmp/TestIRM1.0.0`/TestIRM1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/TestIRM1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

RPC.o: src/rpc/RPC.cpp src/rpc/RPC.h \
		src/rpc/Router.h \
		src/rpc/Stub.h \
		src/rpc/Responder.h \
		src/rpc/Data.h \
		src/rpc/Packet.h \
		src/rpc/Requester.h \
		src/rpc/Channel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RPC.o src/rpc/RPC.cpp

MasterChannel.o: src/master/MasterChannel.cpp src/master/MasterChannel.h \
		src/rpc/Channel.h \
		src/rpc/Data.h \
		src/rpc/Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MasterChannel.o src/master/MasterChannel.cpp

MasterStub.o: src/master/MasterStub.cpp src/master/MasterStub.h \
		src/rpc/Stub.h \
		src/rpc/Responder.h \
		src/rpc/Data.h \
		src/rpc/Packet.h \
		src/rpc/Requester.h \
		src/common/Protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MasterStub.o src/master/MasterStub.cpp

SlaveChannel.o: src/slave/SlaveChannel.cpp src/slave/SlaveChannel.h \
		src/rpc/Channel.h \
		src/rpc/Data.h \
		src/rpc/Packet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SlaveChannel.o src/slave/SlaveChannel.cpp

SlaveStub.o: src/slave/SlaveStub.cpp src/slave/SlaveStub.h \
		src/rpc/Stub.h \
		src/rpc/Responder.h \
		src/rpc/Data.h \
		src/rpc/Packet.h \
		src/rpc/Requester.h \
		src/common/Protocol.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SlaveStub.o src/slave/SlaveStub.cpp

GtkSlave.o: src/slave/GtkSlave.cpp src/slave/SlaveStub.h \
		src/rpc/Stub.h \
		src/rpc/Responder.h \
		src/rpc/Data.h \
		src/rpc/Packet.h \
		src/rpc/Requester.h \
		src/common/Protocol.h \
		src/slave/SlaveChannel.h \
		src/rpc/Channel.h \
		src/rpc/RPC.h \
		src/rpc/Router.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GtkSlave.o src/slave/GtkSlave.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

